;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="SirCppGraph.Location.Car",DevComment="")
+GameplayTagList=(Tag="SirCppGraph.Location.Hostel03Floor2",DevComment="")
+GameplayTagList=(Tag="SirCppGraph.Location.Hostel03Floor2Room",DevComment="")
+GameplayTagList=(Tag="SirCppGraph.Location.HouseHostel01",DevComment="")
+GameplayTagList=(Tag="SirCppGraph.Location.HouseHostel02",DevComment="")
+GameplayTagList=(Tag="SirCppGraph.Location.HouseKiller01",DevComment="")
+GameplayTagList=(Tag="SirCppGraph.Location.HouseKillerDoor",DevComment="")
+GameplayTagList=(Tag="SirCppGraph.Location.HouseKillerDoorOut",DevComment="")
+GameplayTagList=(Tag="SirCppGraph.Location.HouseRich",DevComment="")
+GameplayTagList=(Tag="SirCppGraph.Location.HouseSilver",DevComment="")
+GameplayTagList=(Tag="SirCppGraph.Location.HouseSilverV2",DevComment="")

